# Generated by Django 4.1.1 on 2022-11-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_client_options_product_interested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='interested',
            field=models.PositiveIntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0),
        ),
    ]
